// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-x7g-LSgK3kK3mZpBCtv1BqyTpnNcPEY',
    appId: '1:654402030431:web:332ce029d8f85fb08304ea',
    messagingSenderId: '654402030431',
    projectId: 'city-guide-7233a',
    authDomain: 'city-guide-7233a.firebaseapp.com',
    storageBucket: 'city-guide-7233a.appspot.com',
    measurementId: 'G-NQXN70SDP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOizeRE0UbLCArkxZ1odDClqVRjw1N3rE',
    appId: '1:654402030431:android:0072b6e272821e288304ea',
    messagingSenderId: '654402030431',
    projectId: 'city-guide-7233a',
    storageBucket: 'city-guide-7233a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xPaHv-eaXpKzx8iPkdln56w16RzxJsk',
    appId: '1:654402030431:ios:bd652a4eca24b99c8304ea',
    messagingSenderId: '654402030431',
    projectId: 'city-guide-7233a',
    storageBucket: 'city-guide-7233a.appspot.com',
    iosBundleId: 'com.example.servicesGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xPaHv-eaXpKzx8iPkdln56w16RzxJsk',
    appId: '1:654402030431:ios:5186226fac7750d98304ea',
    messagingSenderId: '654402030431',
    projectId: 'city-guide-7233a',
    storageBucket: 'city-guide-7233a.appspot.com',
    iosBundleId: 'com.example.servicesGuide.RunnerTests',
  );
}
